### ISSUE TITLE
The Mod causes the server to fail to start

### ISSUE THREAD

**Issue by Pau1am** [BlossomMods/BlossomBack#1]
When I install the BlossomBack, the server will not start. The following are related errors

[Server] Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[Server] [22:24:16] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[Server] [22:24:16] [main/WARN]: Mod resolution failed
[Server] [22:24:16] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE blossom-back 2.0.1+1.19 {depends blossom-lib ][Server] [22:24:16] [main/INFO]: Reason: [HARD_DEP blossom-back 2.0.1+1.19 {depends blossom-lib @ [2.3.0]}]
[Server] [22:24:16] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, multiconnect-api, fabric-keybind][Server] [22:24:16] [main/INFO]: Fix: add [], remove [], replace [[blossom-lib 2.3.1+1.19] -> add:blossom-lib 2.3.0 ([[][Server] [22:24:16] [main/ERROR]: Incompatible mod set!
[Server] net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
[Server] A potential solution has been determined:
[Server]         - Replace mod 'BlossomLib' (blossom-lib) 2.3.1+1.19 with version 2.3.0.
[Server] Unmet dependency listing:
[Server]         - Mod 'BlossomBack' (blossom-back) 2.0.1+1.19 requires version 2.3.0 of mod 'BlossomLib' (blossom-lib)![Server]        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.8.jar][Server]        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.8.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.8.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?][Server]        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)

**Comment by CodedSakura** [comment]
god damn fabric version checker...

**Comment by CodedSakura** [comment]
false alarm, forgot to prefix required BlossomLib version with a `^`

**Comment by CodedSakura** [comment]
fixed in 36772459d012bc23b31adf6513cb3f8b952d09b5
