### ISSUE TITLE
After entering the ender portal, the back command is abnormal

### ISSUE THREAD

**Issue by Pau1am** [BlossomMods/BlossomBack#2]
When I enter the_end world through the ender portal and enter the /back command to try to return to the previous teleportation point, I will be teleported to the obsidian platform I just entered the_end world.

**Comment by CodedSakura** [comment]
sorry for the long delay... finally got to fixing this, but can't seem to reproduce this issue at all. what mc version, blossom mod versions & other mods are you using?

**Comment by Pau1am** [comment]
I just tried to reproduce the problem and found that the problem was solved unexpectedly. It seems to be possible to close the issue for now, and I will reopen it if a similar problem occurs later.
