### ISSUE TITLE
/back location is lost on server restart

### ISSUE THREAD

**Issue by justinbchen** [BlossomMods/BlossomBack#3]
Would it be possible to save the location to disk so that the /back location is persistent?

**Comment by CodedSakura** [comment]
theoretically, yes, with some minor code changes, but i really don't see it being practical...

**Comment by justinbchen** [comment]
Why not? In most Spigot/Paper servers I've been in with Essentials, people tend to rely on /back as a persistent temporary warp point and it often ends up quite useful in that regard.

**Comment by CodedSakura** [comment]
wait, so how do you mean persistent? i though persistent meant that it persists across server restarts...

**Comment by justinbchen** [comment]
Yes, that is what I mean. Especially in servers that restart often, it's convenient to know that you won't lose your /back.

**Comment by CodedSakura** [comment]
alright, i'll consider making it persistent

**Comment by CodedSakura** [comment]
the 2.1.0 version now has config options to persist teleports and deaths across server restarts
