### ISSUE TITLE
Modrinth versions

### ISSUE THREAD

**Issue by lieonlion** [BlossomMods/BlossomBack#7]
2.1.1+1.20 is listed as only supporting 1.20.2

![image](https://github.com/BlossomMods/BlossomBack/assets/84919270/2f77c3c2-a879-4367-8f9b-902299fcec7f)

meaning Modrinth won't let you install it for 1.20 or 1.20.1

**Comment by CodedSakura** [comment]
thanks for spotting that! has been fixed now
