### ISSUE TITLE
/lastdeath command doesnt exist?

### ISSUE THREAD

**Issue by D4rkMn** [BlossomMods/BlossomBack#8]
The mod's description says it should add the commands /back and /lastdeath. However after having added it to my server, it only adds /back, not /lastdeath. Is it because the 1.20.1 version isnt updated to have this feature? Or why is it?

**Comment by CodedSakura** [comment]
you need to enable the `/lastdeath` command in the config (`/config/BlossomMods/BlossomBack.json`)

**Comment by D4rkMn** [comment]
Thanks! That did it!
